name: Build and deploy to Hostinger

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch? Replace `main` with your branchâ€™s name
  push:
    branches: [main]
  # Enable manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files to Hostinger
        # This composite action must run in the same build job to access the build directory
        uses: mradilla/hostinger-deploy@v1
        with:
          domain: pomo-focus.com    # Replace with your Hostinger domain
          source-path: ''     # Replace with your build directory (e.g., out, dist, build)
          host: ${{ pomo-focus.HOSTINGER_HOST }}
          port: ${{ pomo-focus.HOSTINGER_PORT }}
          username: ${{ pomo-focus.HOSTINGER_USERNAME }}
          password: ${{ pomo-focus.HOSTINGER_PASSWORD }}
